<a href="https://colab.research.google.com/github/nivanjanapramod/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [9]:
#please provide your answer below this line.
import random

l=[ [ None for y in range( 3 ) ] for x in range( 3 ) ]
for i in range(3):
  for j in range(3):
    l[i][j]=random.randint(1,100)
print(l)

[[40, 46, 56], [18, 5, 2], [98, 99, 17]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [16]:
#please provide your answer below this line.
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [4, 5, 6, 7],
                [8, 9, 7, 8],
                [3, 7, 4, 2]])
print(arr)
reshaped = np.reshape(arr, (2, 8))
print(np.vstack(reshaped))
print(np.hstack(reshaped))

[[1 2 3 4]
 [4 5 6 7]
 [8 9 7 8]
 [3 7 4 2]]
[[1 2 3 4 4 5 6 7]
 [8 9 7 8 3 7 4 2]]
[1 2 3 4 4 5 6 7 8 9 7 8 3 7 4 2]
