<a href="https://colab.research.google.com/github/nivanjanapramod/LEARN.PY/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [6]:
#please provide your answer below this line.
import numpy
a = numpy.arange(1,10).reshape(3,3)
b = numpy.arange(11,20).reshape(3,3)
dot = numpy.dot(a, b)
t=dot.transpose()
print("dot product\n",dot)
print("Transpose\n",t)


dot product
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]
Transpose
 [[ 90 216 342]
 [ 96 231 366]
 [102 246 390]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [16]:
#please provide your answer below this line.
import numpy

a = numpy.array([55,25,15,30,44,2,11,45,77]).reshape(3,3)
print("determinant\n",numpy.linalg.det(a))

determinant
 137180.0000000001
